!include_try /usr/share/dovecot/protocols.d/*.protocol
protocols = imap lmtp pop3

#log_path = /var/log/mail/dovecot.log
#info_log_path = /var/log/mail/dovecot-info.log
#debug_log_path = /var/log/mail/dovecot-debug.log
#verbose_ssl=yes
#auth_verbose=yes
#auth_debug=yes
#mail_debug=yes

dict {
  quota = mysql:/etc/dovecot/dovecot-quota-sql.conf.ext
  lastlogin = mysql:/etc/dovecot/dovecot-lastlogin-sql.conf.ext
}

!include conf.d/*.conf
!include_try local.conf
