service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 0
  }
  inet_listener pop3s {
    port = 995
  }
}

service submission-login {
  inet_listener submission {
  }
}

service lmtp {
  unix_listener lmtp {
  }
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

service imap {
}

service pop3 {
}

service submission {
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }

  unix_listener auth-userdb {
    mode = 0600
    user = vmail
  }

  user = dovecot
}

service auth-worker {
  user = vmail
}

service dict {
    unix_listener dict {
    mode = 0660
    user = vmail
    group = vmail
  }
}

service quota-warning {
  executable = script /usr/local/bin/quota-warning.sh
  user = vmail
  unix_listener quota-warning {
    mode = 660
    user = vmail
  }
}

service stats {
  unix_listener stats-reader {
    user = vmail
    mode = 0666
  }

  unix_listener stats-writer {
    user = vmail
    mode = 0666
  }
}
